<?php
/**
 * Minimal Booqable API v4 (JSON:API) client.
 *
 * Auth: Bearer access token, generated by the store owner at
 * https://{company}.booqable.com/employees/current — never the legacy
 * v1 `?api_key=` query-param scheme.
 *
 * @package Booqable_Rental_Core
 */

namespace Booqable_Rental_Core;

if ( ! defined( 'WPINC' ) ) {
	die;
}

class Client {

	/**
	 * @return string
	 */
	protected function get_company_slug() {
		return trim( (string) get_option( 'booqable_core_company_slug', '' ) );
	}

	/**
	 * @return string
	 */
	protected function get_access_token() {
		return trim( (string) get_option( 'booqable_core_access_token', '' ) );
	}

	/**
	 * @return bool
	 */
	public function is_configured() {
		return '' !== $this->get_company_slug() && '' !== $this->get_access_token();
	}

	/**
	 * @param string $path   e.g. "collections" or "product_groups".
	 * @param array  $query  Extra query args (JSON:API page/filter/include params).
	 * @return array|\WP_Error Decoded JSON body on success, WP_Error on failure.
	 */
	public function get( $path, $query = array() ) {
		if ( ! $this->is_configured() ) {
			return new \WP_Error(
				'booqable_core_not_configured',
				__( 'Booqable API is not configured yet — add your company and access token under Settings → Booqable Rental Core.', 'booqable-rental-core' )
			);
		}

		$slug = $this->get_company_slug();
		$url  = sprintf( 'https://%s.booqable.com/api/4/%s', $slug, ltrim( $path, '/' ) );

		if ( ! empty( $query ) ) {
			$url = add_query_arg( $query, $url );
		}

		$response = wp_remote_get(
			$url,
			array(
				'timeout' => 10,
				'headers' => array(
					'Authorization' => 'Bearer ' . $this->get_access_token(),
					'Accept'        => 'application/json',
				),
			)
		);

		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$code = wp_remote_retrieve_response_code( $response );
		$body = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( $code < 200 || $code >= 300 ) {
			$message = is_array( $body ) && isset( $body['errors'][0]['title'] )
				? $body['errors'][0]['title']
				: sprintf( /* translators: %d: HTTP status code */ __( 'Booqable API returned HTTP %d.', 'booqable-rental-core' ), $code );

			return new \WP_Error( 'booqable_core_api_error', $message, array( 'status' => $code ) );
		}

		return is_array( $body ) ? $body : array();
	}

	/**
	 * Lightweight connectivity check used by the Settings page's
	 * "Test Connection" button — asks for a single collection so it stays
	 * fast regardless of catalog size.
	 *
	 * @return true|\WP_Error
	 */
	public function test_connection() {
		$result = $this->get( 'collections', array( 'page' => array( 'size' => 1 ) ) );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return true;
	}

	/**
	 * @return array|\WP_Error List of ['id', 'name', 'slug', 'image_url'] collections.
	 */
	public function get_collections() {
		$result = $this->get( 'collections', array( 'page' => array( 'size' => 100 ) ) );
		if ( is_wp_error( $result ) ) {
			return $result;
		}

		$collections = array();
		foreach ( (array) ( $result['data'] ?? array() ) as $item ) {
			$attributes    = $item['attributes'] ?? array();
			$collections[] = array(
				'id'        => $item['id'] ?? '',
				'name'      => $attributes['name'] ?? '',
				'slug'      => $attributes['slug'] ?? '',
				// Confirmed against a live /api/4/collections response.
				'image_url' => $attributes['image_large_url'] ?? ( $attributes['image_url'] ?? '' ),
			);
		}
		return $collections;
	}

	/**
	 * @param string|null $collection_id Filter to one collection, or null for all.
	 * @param int         $limit
	 * @return array|\WP_Error List of simplified product group records.
	 */
	public function get_product_groups( $collection_id = null, $limit = 24 ) {
		$query = array(
			'page'   => array( 'size' => max( 1, (int) $limit ) ),
			'filter' => array( 'show_in_store' => 'true' ),
			'sort'   => 'sorting_weight',
		);
		if ( $collection_id ) {
			$query['filter']['collection_id'] = $collection_id;
		}

		$result = $this->get( 'product_groups', $query );
		if ( is_wp_error( $result ) ) {
			return $result;
		}

		$groups = array();
		foreach ( (array) ( $result['data'] ?? array() ) as $item ) {
			$a        = $item['attributes'] ?? array();
			$groups[] = array(
				'id'             => $item['id'] ?? '',
				'name'           => $a['name'] ?? '',
				'slug'           => $a['slug'] ?? '',
				'description'    => $a['excerpt'] ?? ( $a['description'] ?? '' ),
				'photo_url'      => $a['photo_url'] ?? '',
				'price_in_cents' => (int) ( $a['base_price_in_cents'] ?? 0 ),
				'price_period'   => $a['price_period'] ?? '',
				'trackable'      => ! empty( $a['trackable'] ),
			);
		}
		return $groups;
	}

	/**
	 * @param string $id Product group ID.
	 * @return array|\WP_Error
	 */
	public function get_product_group( $id ) {
		$result = $this->get( 'product_groups/' . rawurlencode( $id ) );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		$a = $result['data']['attributes'] ?? array();
		return array(
			'id'             => $result['data']['id'] ?? $id,
			'name'           => $a['name'] ?? '',
			'slug'           => $a['slug'] ?? '',
			'description'    => $a['description'] ?? '',
			'photo_url'      => $a['photo_url'] ?? '',
			'price_in_cents' => (int) ( $a['base_price_in_cents'] ?? 0 ),
			'price_period'   => $a['price_period'] ?? '',
			'trackable'      => ! empty( $a['trackable'] ),
		);
	}

	/**
	 * The store's own Company record — used only for its `currency` (ISO
	 * 4217, lowercase, e.g. `"idr"`) so prices can be displayed correctly
	 * without a manual "set your currency" settings field. Only maps the
	 * handful of fields actually used; the real response also carries the
	 * store owner's address/phone/email etc., none of which this plugin
	 * has any reason to expose further than "safe, cacheable, public".
	 *
	 * @return array|\WP_Error ['currency','name','default_timezone'].
	 */
	public function get_company() {
		$result = $this->get( 'companies/current' );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		$a = $result['data']['attributes'] ?? array();
		return array(
			'currency'         => strtolower( $a['currency'] ?? 'usd' ),
			'name'             => $a['name'] ?? '',
			'default_timezone' => $a['default_timezone'] ?? '',
		);
	}

	/**
	 * @return array|\WP_Error List of ['id','name'] locations.
	 */
	public function get_locations() {
		$result = $this->get( 'locations', array( 'page' => array( 'size' => 50 ) ) );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		$locations = array();
		foreach ( (array) ( $result['data'] ?? array() ) as $item ) {
			$locations[] = array(
				'id'   => $item['id'] ?? '',
				'name' => $item['attributes']['name'] ?? '',
			);
		}
		return $locations;
	}

	/**
	 * Runs several independent Booqable calls concurrently instead of one
	 * after another, via the `Requests` library WordPress core already
	 * bundles (`WpOrg\Requests\Requests` — the same library WP_Http's own
	 * Curl transport uses internally, not a new dependency). Only ever call
	 * this with calls that genuinely don't depend on each other's result —
	 * e.g. creating the order and looking up the customer by email at the
	 * same time. See cart-and-checkout.md#performance-note for exactly
	 * which Checkout steps qualify and which were deliberately kept
	 * sequential (anything that writes to a resource another call in the
	 * same batch also writes to).
	 *
	 * @param array $calls Keyed by caller-chosen name => [method, path, body, query]
	 *                      tuples — the same four things request()'s
	 *                      parameters are, one tuple per call.
	 * @return array Same keys, each value the decoded JSON body or a
	 *               WP_Error — identical in shape to what request() returns
	 *               for a single call.
	 */
	public function request_multiple( array $calls ) {
		if ( ! $this->is_configured() ) {
			$error = new \WP_Error(
				'booqable_core_not_configured',
				__( 'Booqable API is not configured yet — add your company and access token under Settings → Booqable Rental Core.', 'booqable-rental-core' )
			);
			return array_fill_keys( array_keys( $calls ), $error );
		}

		// Defensive fallback for the (unusual) host where the bundled
		// Requests library isn't loadable — correctness over speed, just
		// run the same calls one at a time through the normal path.
		if ( ! class_exists( '\WpOrg\Requests\Requests' ) ) {
			$results = array();
			foreach ( $calls as $key => $call ) {
				list( $method, $path, $body, $query ) = array_pad( $call, 4, null );
				$results[ $key ] = $this->request( $method, $path, $body, $query ?? array() );
			}
			return $results;
		}

		$slug     = $this->get_company_slug();
		$token    = $this->get_access_token();
		$requests = array();
		foreach ( $calls as $key => $call ) {
			list( $method, $path, $body, $query ) = array_pad( $call, 4, null );
			$url = sprintf( 'https://%s.booqable.com/api/4/%s', $slug, ltrim( $path, '/' ) );
			if ( ! empty( $query ) ) {
				$url = add_query_arg( $query, $url );
			}
			$requests[ $key ] = array(
				'url'     => $url,
				'headers' => array(
					'Authorization' => 'Bearer ' . $token,
					'Accept'        => 'application/json',
					'Content-Type'  => 'application/json',
				),
				'data'    => null !== $body ? wp_json_encode( $body ) : '',
				'type'    => $method,
			);
		}

		$responses = \WpOrg\Requests\Requests::request_multiple( $requests, array( 'timeout' => 15 ) );

		$results = array();
		foreach ( $responses as $key => $response ) {
			$results[ $key ] = $this->normalize_multi_response( $response );
		}
		return $results;
	}

	/**
	 * @param \WpOrg\Requests\Response|\Exception $response One entry from
	 *                                                        request_multiple()'s
	 *                                                        return value.
	 * @return array|\WP_Error
	 */
	protected function normalize_multi_response( $response ) {
		// A genuine transport failure (DNS, connection refused, malformed
		// response) — request_multiple() catches these per-call rather than
		// throwing, unlike an HTTP error status, which never throws here
		// (same contract request() has: caller checks the status code).
		if ( $response instanceof \Exception ) {
			return new \WP_Error( 'booqable_core_api_error', $response->getMessage() );
		}

		$code = (int) $response->status_code;
		$body = json_decode( (string) $response->body, true );

		if ( $code < 200 || $code >= 300 ) {
			$message = is_array( $body ) && isset( $body['errors'][0]['title'] )
				? $body['errors'][0]['title'] . ( isset( $body['errors'][0]['detail'] ) ? ': ' . $body['errors'][0]['detail'] : '' )
				: sprintf( /* translators: %d: HTTP status code */ __( 'Booqable API returned HTTP %d.', 'booqable-rental-core' ), $code );

			return new \WP_Error( 'booqable_core_api_error', $message, array( 'status' => $code, 'body' => $body ) );
		}

		return is_array( $body ) ? $body : array();
	}

	/**
	 * Fires a write with no interest in the response — for best-effort side
	 * calls only (currently just the optional phone Property below), whose
	 * failure the caller already treats as ignorable and which must never
	 * add their own latency to whatever the caller is doing. Uses WP_Http's
	 * own `blocking => false` idiom (the same one WP core uses for its own
	 * fire-and-forget pings) rather than request_multiple() — there's
	 * nothing to wait for, so there's nothing to batch.
	 *
	 * @param string $method
	 * @param string $path
	 * @param array  $body
	 * @return void
	 */
	protected function fire_and_forget( $method, $path, $body ) {
		if ( ! $this->is_configured() ) {
			return;
		}
		$slug = $this->get_company_slug();
		$url  = sprintf( 'https://%s.booqable.com/api/4/%s', $slug, ltrim( $path, '/' ) );
		wp_remote_request(
			$url,
			array(
				'method'   => $method,
				'timeout'  => 0.01,
				'blocking' => false,
				'headers'  => array(
					'Authorization' => 'Bearer ' . $this->get_access_token(),
					'Accept'        => 'application/json',
					'Content-Type'  => 'application/json',
				),
				'body'     => wp_json_encode( $body ),
			)
		);
	}

	/**
	 * Shared authenticated request used by every write (POST/PATCH/DELETE).
	 * `get()` stays the read-only entry point above; this is its write-capable
	 * sibling so both share the same auth/error handling.
	 *
	 * @param string     $method GET|POST|PATCH|DELETE.
	 * @param string     $path
	 * @param array|null $body   Decoded JSON:API body, or null for no body.
	 * @param array      $query
	 * @return array|\WP_Error Decoded JSON body on success, WP_Error on failure.
	 */
	protected function request( $method, $path, $body = null, $query = array() ) {
		if ( ! $this->is_configured() ) {
			return new \WP_Error(
				'booqable_core_not_configured',
				__( 'Booqable API is not configured yet — add your company and access token under Settings → Booqable Rental Core.', 'booqable-rental-core' )
			);
		}

		$slug = $this->get_company_slug();
		$url  = sprintf( 'https://%s.booqable.com/api/4/%s', $slug, ltrim( $path, '/' ) );
		if ( ! empty( $query ) ) {
			$url = add_query_arg( $query, $url );
		}

		$args = array(
			'method'  => $method,
			'timeout' => 15,
			'headers' => array(
				'Authorization' => 'Bearer ' . $this->get_access_token(),
				'Accept'        => 'application/json',
				'Content-Type'  => 'application/json',
			),
		);
		if ( null !== $body ) {
			$args['body'] = wp_json_encode( $body );
		}

		$response = wp_remote_request( $url, $args );
		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$code = wp_remote_retrieve_response_code( $response );
		$body = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( $code < 200 || $code >= 300 ) {
			$message = is_array( $body ) && isset( $body['errors'][0]['title'] )
				? $body['errors'][0]['title'] . ( isset( $body['errors'][0]['detail'] ) ? ': ' . $body['errors'][0]['detail'] : '' )
				: sprintf( /* translators: %d: HTTP status code */ __( 'Booqable API returned HTTP %d.', 'booqable-rental-core' ), $code );

			return new \WP_Error( 'booqable_core_api_error', $message, array( 'status' => $code, 'body' => $body ) );
		}

		return is_array( $body ) ? $body : array();
	}

	/**
	 * All products (not product groups) that are for sale in the store,
	 * flat — used to resolve the actual bookable Product id behind each
	 * Product Group card (`Products cache::get()` filters by
	 * `product_group_id` client-side rather than one API call per group).
	 *
	 * @return array|\WP_Error
	 */
	public function get_products( $limit = 200 ) {
		$result = $this->get(
			'products',
			array(
				'page'   => array( 'size' => max( 1, (int) $limit ) ),
				'filter' => array( 'show_in_store' => 'true' ),
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}

		$products = array();
		foreach ( (array) ( $result['data'] ?? array() ) as $item ) {
			$a          = $item['attributes'] ?? array();
			$products[] = array(
				'id'               => $item['id'] ?? '',
				'product_group_id' => $a['product_group_id'] ?? '',
				'name'             => $a['name'] ?? '',
				'trackable'        => ! empty( $a['trackable'] ),
				'has_variations'   => ! empty( $a['has_variations'] ),
				'product_type'     => $a['product_type'] ?? '',
				'price_in_cents'   => (int) ( $a['base_price_in_cents'] ?? 0 ),
				'price_period'     => $a['price_period'] ?? '',
			);
		}
		return $products;
	}

	/**
	 * Create a cart-equivalent Order. Confirmed live: only `starts_at` /
	 * `stops_at` are accepted as attributes — `location_id` is neither a
	 * writable attribute nor relationship at creation time, Booqable
	 * auto-assigns the account's default location (`start_location_id` /
	 * `stop_location_id` come back populated regardless).
	 *
	 * @param string $starts_at ISO 8601.
	 * @param string $stops_at  ISO 8601.
	 * @return array|\WP_Error ['id','status','item_count','total_in_cents','grand_total_in_cents','starts_at','stops_at'].
	 */
	public function create_order( $starts_at, $stops_at ) {
		list( $method, $path, $body, $query ) = $this->order_create_spec( $starts_at, $stops_at );
		$result                               = $this->request( $method, $path, $body, $query );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return $this->map_order( $result['data'] ?? array() );
	}

	/**
	 * The [method, path, body, query] tuple create_order() sends — split out
	 * so Checkout::submit() can hand it to request_multiple() alongside the
	 * customer lookup, instead of only ever being able to call this
	 * sequentially. Both create_order() above and Checkout use this same
	 * tuple, so the request shape only lives in one place.
	 *
	 * @param string $starts_at ISO 8601.
	 * @param string $stops_at  ISO 8601.
	 * @return array
	 */
	public function order_create_spec( $starts_at, $stops_at ) {
		return array(
			'POST',
			'orders',
			array(
				'data' => array(
					'type'       => 'orders',
					'attributes' => array(
						'starts_at' => $starts_at,
						'stops_at'  => $stops_at,
					),
				),
			),
			array(),
		);
	}

	/**
	 * @param string $order_id
	 * @return array|\WP_Error|null Null when the order genuinely no longer
	 *                              exists (404) — callers should treat that
	 *                              as "cart is gone, start a new one", not
	 *                              as a hard failure.
	 */
	public function get_order( $order_id ) {
		$result = $this->request( 'GET', 'orders/' . rawurlencode( $order_id ) );
		if ( is_wp_error( $result ) ) {
			$status = $result->get_error_data()['status'] ?? 0;
			return 404 === $status ? null : $result;
		}
		return $this->map_order( $result['data'] ?? array() );
	}

	/**
	 * Public (not protected) because Checkout::submit() needs to map a raw
	 * order resource that came back through request_multiple() — the batch
	 * path below, not the single-call request() every other method here
	 * still uses.
	 *
	 * @param array $resource Raw JSON:API `orders` resource.
	 * @return array
	 */
	public function map_order( $resource ) {
		$a = $resource['attributes'] ?? array();
		return array(
			'id'                   => $resource['id'] ?? '',
			'status'               => $a['status'] ?? '',
			'item_count'           => (int) ( $a['item_count'] ?? 0 ),
			'total_in_cents'       => (int) ( $a['total_in_cents'] ?? 0 ),
			'grand_total_in_cents' => (int) ( $a['grand_total_in_cents'] ?? 0 ),
			'starts_at'            => $a['starts_at'] ?? '',
			'stops_at'             => $a['stops_at'] ?? '',
			// `shortage` is deprecated by Booqable in favor of `location_shortage`
			// (confirmed in the live docs) — both kept for now, callers should
			// prefer location_shortage.
			'shortage'             => ! empty( $a['shortage'] ),
			'location_shortage'    => ! empty( $a['location_shortage'] ),
			'number'               => $a['number'] ?? null,
			'customer_id'          => $a['customer_id'] ?? null,
			// One of payment_due|partially_paid|paid|overpaid|process_deposit —
			// Booqable computes this from the order's PaymentCharges, we never
			// set it directly. See references/payments.md.
			'payment_status'       => $a['payment_status'] ?? 'payment_due',
			'updated_at'           => $a['updated_at'] ?? '',
		);
	}

	/**
	 * Finds an existing Customer by email (avoids duplicate customer records
	 * for a repeat visitor) or creates a new one. Confirmed live:
	 * `filter[email][eq]` on `GET /customers` works for the lookup.
	 *
	 * @param string $name
	 * @param string $email
	 * @param string $phone Optional. Stored as a `phone`-type Property (Customers
	 *                      have no flat `phone` attribute — confirmed against the
	 *                      live Fields table; phone/address are Properties).
	 * @return string|\WP_Error Customer id.
	 */
	public function find_or_create_customer( $name, $email, $phone = '' ) {
		$existing_id = $this->lookup_customer_by_email( $email );
		return null !== $existing_id ? $existing_id : $this->create_customer( $name, $email, $phone );
	}

	/**
	 * The [method, path, body, query] tuple for looking a customer up by
	 * email — split out (rather than only living inside
	 * lookup_customer_by_email()) so Checkout::submit() can run it in the
	 * same request_multiple() batch as order creation, which has no
	 * dependency on it either way.
	 *
	 * @param string $email
	 * @return array
	 */
	public function customer_lookup_spec( $email ) {
		return array( 'GET', 'customers', null, array( 'filter' => array( 'email' => array( 'eq' => $email ) ) ) );
	}

	/**
	 * @param string $email
	 * @return string|null Customer id if one already exists for this email,
	 *                      null if not found *or* if the lookup itself
	 *                      failed (a network hiccup here just means "create
	 *                      one instead" — the same fall-through contract
	 *                      find_or_create_customer() always had).
	 */
	public function lookup_customer_by_email( $email ) {
		list( $method, $path, $body, $query ) = $this->customer_lookup_spec( $email );
		$existing                             = $this->request( $method, $path, $body, $query );
		if ( ! is_wp_error( $existing ) && ! empty( $existing['data'][0]['id'] ) ) {
			return $existing['data'][0]['id'];
		}
		return null;
	}

	/**
	 * The [method, path, body, query] tuple for creating a customer — split
	 * out so Checkout::submit() can run it in the same request_multiple()
	 * batch as the line-booking calls when no existing customer was found
	 * (a new customer record has no dependency on the order's lines, or
	 * vice versa).
	 *
	 * @param string $name
	 * @param string $email
	 * @return array
	 */
	public function customer_create_spec( $name, $email ) {
		return array(
			'POST',
			'customers',
			array(
				'data' => array(
					'type'       => 'customers',
					'attributes' => array(
						'name'  => $name,
						'email' => $email,
					),
				),
			),
			array(),
		);
	}

	/**
	 * Always creates a fresh Customer — no email lookup here, that's
	 * lookup_customer_by_email()'s job, kept separate so the two can run in
	 * the same parallel batch as other checkout calls without depending on
	 * each other.
	 *
	 * @param string $name
	 * @param string $email
	 * @param string $phone Optional — see find_or_create_customer()'s docblock.
	 * @return string|\WP_Error Customer id.
	 */
	public function create_customer( $name, $email, $phone = '' ) {
		list( $method, $path, $body, $query ) = $this->customer_create_spec( $name, $email );
		$created                              = $this->request( $method, $path, $body, $query );
		if ( is_wp_error( $created ) ) {
			return $created;
		}
		$customer_id = $created['data']['id'] ?? '';
		if ( '' === $customer_id ) {
			return new \WP_Error( 'booqable_core_no_customer', __( 'Booqable did not return a customer id.', 'booqable-rental-core' ) );
		}

		if ( '' !== trim( (string) $phone ) ) {
			$this->attach_customer_phone( $customer_id, $phone );
		}

		return $customer_id;
	}

	/**
	 * Best-effort phone Property on a Customer — fired-and-forgotten (see
	 * fire_and_forget()) since its own live docs confirm phone/address are
	 * Properties, not a flat Customer attribute, and losing this one field
	 * must never block or slow down checkout.
	 *
	 * @param string $customer_id
	 * @param string $phone
	 * @return void
	 */
	public function attach_customer_phone( $customer_id, $phone ) {
		$this->fire_and_forget(
			'POST',
			'properties',
			array(
				'data' => array(
					'type'       => 'properties',
					'attributes' => array(
						'name'          => 'Phone',
						'property_type' => 'phone',
						'value'         => $phone,
						'owner_id'      => $customer_id,
						'owner_type'    => 'customers',
					),
				),
			)
		);
	}

	/**
	 * @param string $order_id
	 * @param string $customer_id
	 * @return array|\WP_Error Mapped order.
	 */
	public function set_order_customer( $order_id, $customer_id ) {
		$result = $this->request(
			'PATCH',
			'orders/' . rawurlencode( $order_id ),
			array(
				'data' => array(
					'id'         => $order_id,
					'type'       => 'orders',
					'attributes' => array( 'customer_id' => $customer_id ),
				),
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return $this->map_order( $result['data'] ?? array() );
	}

	/**
	 * Reserves the cart order — the step that actually locks inventory
	 * against other visitors and gives the order a real, staff-visible
	 * number (a `new` order is invisible in the Booqable dashboard except to
	 * the employee/token that created it, confirmed in the live docs' "How
	 * to Build a Booking Flow" section). This is the "checkout submitted"
	 * moment in our flow, not "payment confirmed" — see references/payments.md.
	 *
	 * @param string $order_id
	 * @return array|\WP_Error Mapped order. A shortage conflict (another
	 *                         visitor took the last unit first) comes back as
	 *                         a WP_Error with Booqable's own detail.
	 */
	public function reserve_order( $order_id ) {
		$result = $this->request(
			'POST',
			'order_status_transitions',
			array(
				'data' => array(
					'type'       => 'order_status_transitions',
					'attributes' => array(
						'order_id'        => $order_id,
						'transition_from' => 'new',
						'transition_to'   => 'reserved',
					),
				),
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return $this->get_order( $order_id );
	}

	/**
	 * Cancels an order — releases any reserved inventory back to the pool.
	 * Used both by the checkout-abandonment cron sweep and available for a
	 * future admin action. Confirmed live: irreversible (Booqable does not
	 * allow resurrecting a canceled order; a fresh cart is created instead).
	 *
	 * @param string $order_id
	 * @param string $from_status Current status (`new`|`draft`|`reserved`).
	 * @return true|\WP_Error
	 */
	public function cancel_order( $order_id, $from_status ) {
		$result = $this->request(
			'POST',
			'order_status_transitions',
			array(
				'data' => array(
					'type'       => 'order_status_transitions',
					'attributes' => array(
						'order_id'        => $order_id,
						'transition_from' => $from_status,
						'transition_to'   => 'canceled',
					),
				),
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return true;
	}

	/**
	 * Orders in one of `$statuses` that haven't been touched since before
	 * `$before_iso` — used by the order-expiry cron sweep to find abandoned
	 * carts and unpaid reservations. Confirmed live: `filter[updated_at][lt]`
	 * is accepted on `GET /orders`.
	 *
	 * @param array  $statuses
	 * @param string $before_iso ISO 8601.
	 * @return array|\WP_Error List of mapped orders.
	 */
	public function get_stale_orders( $statuses, $before_iso ) {
		$orders = array();
		foreach ( $statuses as $status ) {
			$result = $this->request(
				'GET',
				'orders',
				null,
				array(
					'filter' => array(
						'status'     => array( 'eq' => $status ),
						'updated_at' => array( 'lt' => $before_iso ),
					),
					'page'   => array( 'size' => 100 ),
				)
			);
			if ( is_wp_error( $result ) ) {
				return $result;
			}
			foreach ( (array) ( $result['data'] ?? array() ) as $item ) {
				$orders[] = $this->map_order( $item );
			}
		}
		return $orders;
	}

	/**
	 * Book a quantity of a Product onto an Order — the *only* way to add a
	 * rental product that actually allocates inventory (plain `POST /lines`
	 * only creates non-inventory "custom charge" lines, confirmed live and
	 * matches the API's own warning under the Lines resource docs).
	 *
	 * `mode=infer_planning` is the safe default for a cart "Add" button: it
	 * reuses the existing Planning/Line for this product on this order if
	 * one exists (increasing quantity) or creates a new one — callers don't
	 * need to track planning ids themselves.
	 *
	 * @param string $order_id
	 * @param string $product_id
	 * @param int    $quantity
	 * @return array|\WP_Error Mapped line: ['id','item_id','quantity','price_in_cents','title'].
	 *                         A shortage/inventory conflict comes back as a
	 *                         WP_Error whose message is Booqable's own detail.
	 */
	public function book_product( $order_id, $product_id, $quantity ) {
		list( $method, $path, $body, $query ) = $this->book_product_spec( $order_id, $product_id, $quantity );
		$result                               = $this->request( $method, $path, $body, $query );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return $this->extract_line( $result );
	}

	/**
	 * The [method, path, body, query] tuple book_product() sends — split out
	 * so Checkout::submit() can book every cart line in one
	 * request_multiple() batch (each line's booking only depends on
	 * $order_id, never on the other lines) instead of one HTTP round trip
	 * per line.
	 *
	 * @param string $order_id
	 * @param string $product_id
	 * @param int    $quantity
	 * @return array
	 */
	public function book_product_spec( $order_id, $product_id, $quantity ) {
		return array(
			'POST',
			'order_fulfillments',
			array(
				'data' => array(
					'type'       => 'order_fulfillments',
					'attributes' => array(
						'order_id' => $order_id,
						'actions'  => array(
							array(
								'action'     => 'book_product',
								'mode'       => 'infer_planning',
								'product_id' => $product_id,
								'quantity'   => max( 1, (int) $quantity ),
							),
						),
					),
				),
			),
			array( 'include' => 'changed_lines' ),
		);
	}

	/**
	 * Pulls the changed `lines` resource out of an order_fulfillments
	 * response's `included` array (requested via `?include=changed_lines`).
	 * Public (not folded back into book_product()) so Checkout::submit()
	 * can use the same extraction for a result that came back through
	 * request_multiple() instead of request().
	 *
	 * @param array $result Decoded order_fulfillments response body.
	 * @return array|\WP_Error Mapped line.
	 */
	public function extract_line( $result ) {
		foreach ( (array) ( $result['included'] ?? array() ) as $included ) {
			if ( 'lines' === ( $included['type'] ?? '' ) ) {
				return $this->map_line( $included );
			}
		}
		return new \WP_Error( 'booqable_core_no_line', __( 'Booqable did not return a line for this booking.', 'booqable-rental-core' ) );
	}

	/**
	 * @param string $line_id
	 * @param int    $quantity
	 * @return array|\WP_Error Mapped line.
	 */
	public function update_line_quantity( $line_id, $quantity ) {
		$result = $this->request(
			'PATCH',
			'lines/' . rawurlencode( $line_id ),
			array(
				'data' => array(
					'id'         => $line_id,
					'type'       => 'lines',
					'attributes' => array( 'quantity' => max( 1, (int) $quantity ) ),
				),
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return $this->map_line( $result['data'] ?? array() );
	}

	/**
	 * Archives the line (Booqable's own "delete" — the record is kept,
	 * flagged `archived: true`, and stops counting toward the order).
	 *
	 * @param string $line_id
	 * @return true|\WP_Error
	 */
	public function remove_line( $line_id ) {
		$result = $this->request( 'DELETE', 'lines/' . rawurlencode( $line_id ) );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return true;
	}

	/**
	 * @param string $order_id
	 * @return array|\WP_Error List of mapped lines, `archived` excluded.
	 */
	public function get_lines_for_order( $order_id ) {
		$result = $this->request( 'GET', 'lines', null, array( 'filter' => array( 'order_id' => $order_id ) ) );
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		$lines = array();
		foreach ( (array) ( $result['data'] ?? array() ) as $item ) {
			if ( ! empty( $item['attributes']['archived'] ) ) {
				continue;
			}
			$lines[] = $this->map_line( $item );
		}
		return $lines;
	}

	/**
	 * @param array $resource Raw JSON:API `lines` resource.
	 * @return array
	 */
	protected function map_line( $resource ) {
		$a = $resource['attributes'] ?? array();
		return array(
			'id'             => $resource['id'] ?? '',
			'item_id'        => $a['item_id'] ?? '',
			'planning_id'    => $a['planning_id'] ?? '',
			'title'          => $a['title'] ?? '',
			'quantity'       => (int) ( $a['quantity'] ?? 0 ),
			'price_each_in_cents' => (int) ( $a['price_each_in_cents'] ?? 0 ),
			'price_in_cents' => (int) ( $a['price_in_cents'] ?? 0 ),
		);
	}

	/**
	 * Quantity available for one item at one location over a date range.
	 * Confirmed against a live response: `inventory_availabilities` requires
	 * exactly `item_id, location_id, from, till` as filters (the API's own
	 * validation error is what revealed this — not documented clearly), and
	 * returns **one aggregate record for the whole range**, not one entry
	 * per day (the field names — `available`, `plannable` — were also only
	 * confirmed by inspecting a live response, not from docs).
	 *
	 * Only meaningful for trackable/stock-managed items; non-trackable
	 * products (services, untracked bulk items) have no quantity ceiling —
	 * callers should treat those as always-available and skip this call.
	 *
	 * @param string $item_id     Product (not product group) ID.
	 * @param string $location_id
	 * @param string $from        Y-m-d.
	 * @param string $till        Y-m-d.
	 * @return array|\WP_Error ['available'=>int,'plannable'=>int] or empty array if
	 *                         Booqable has no data for this range (treat as available).
	 */
	public function get_inventory_availability( $item_id, $location_id, $from, $till ) {
		$result = $this->get(
			'inventory_availabilities',
			array(
				'filter' => array(
					'item_id'     => $item_id,
					'location_id' => $location_id,
					'from'        => $from,
					'till'        => $till,
				),
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		$a = $result['data'][0]['attributes'] ?? array();
		if ( empty( $a ) ) {
			return array();
		}
		return array(
			'available' => (int) ( $a['available'] ?? 0 ),
			'plannable' => (int) ( $a['plannable'] ?? 0 ),
		);
	}

	/**
	 * @param string $order_id
	 * @param string $starts_at ISO 8601.
	 * @param string $stops_at  ISO 8601.
	 * @return array|\WP_Error Mapped order.
	 */
	public function update_order( $order_id, $starts_at, $stops_at ) {
		$result = $this->request(
			'PATCH',
			'orders/' . rawurlencode( $order_id ),
			array(
				'data' => array(
					'id'         => $order_id,
					'type'       => 'orders',
					'attributes' => array(
						'starts_at' => $starts_at,
						'stops_at'  => $stops_at,
					),
				),
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}
		return $this->map_order( $result['data'] ?? array() );
	}
}
